{
    'name': 'Gestión Profesional de Tarifas Logísticas',
    'version': '1.1.1',
    'author': 'Alphaqueb Consulting',
    'category': 'Operations/Logistics',
    'summary': 'Control histórico de tarifas y catálogo editable de fletes marítimos',
    'depends': ['base', 'mail', 'contacts'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/partner_category_data.xml',
        'data/tarifario_month_data.xml',
        'views/tarifario_views.xml',
        'views/tarifario_menus.xml',
        'views/dashboard_kpi.xml',
    ],
    'application': True,
    'installable': True,
    'license': 'LGPL-3',
}